// <auto-generated />
using System;
using AspMvcBiblio.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AspMvcBiblio.Data.Migrations
{
    [DbContext(typeof(BiblioContext))]
    [Migration("20230515092559_BibliothequeKeywords1")]
    partial class BibliothequeKeywords1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AspMvcBiblio.Entities.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Jane",
                            LastName = "Austen"
                        });
                });

            modelBuilder.Entity("AspMvcBiblio.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CopiesNumber")
                        .HasColumnType("int");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("ServiceDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CopiesNumber = 1,
                            ISBN = "2-7654-1005-4",
                            ServiceDate = new DateTime(2012, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Orgueil et Préjugés"
                        });
                });

            modelBuilder.Entity("AspMvcBiblio.Entities.Keyword", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("KeyWords");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Word = "mariage"
                        },
                        new
                        {
                            Id = 2,
                            Word = "meurtre"
                        },
                        new
                        {
                            Id = 3,
                            Word = "été"
                        },
                        new
                        {
                            Id = 4,
                            Word = "voyage"
                        });
                });

            modelBuilder.Entity("AspMvcBiblio.Entities.Reader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Readers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "Ermane.Pourmohtasham@mail.com",
                            FirstName = "Ermane",
                            LastName = "Pourmohtasham",
                            Phone = "0606060606"
                        },
                        new
                        {
                            Id = 2,
                            Email = "Jean.Valjean@mail.com",
                            FirstName = "Jean",
                            LastName = "Valjean",
                            Phone = "0676869616"
                        });
                });

            modelBuilder.Entity("AspMvcBiblio.Entities.Theme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("DomainName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Themes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Les livres de suspense sont des thrillers qui tiennent les lecteurs en haleine jusqu'à la fin. Ils ont souvent des intrigues complexes, des personnages intrigants et des rebondissements inattendus. \"Gone Girl\" de Gillian Flynn est un exemple de livre de suspense qui raconte l'histoire d'un mari qui devient le suspect principal dans la disparition de sa femme",
                            DomainName = "Suspense "
                        },
                        new
                        {
                            Id = 2,
                            Description = "Les biographies sont des livres qui racontent la vie d'une personne réelle. Ils peuvent se concentrer sur la vie entière de la personne ou sur une période spécifique de sa vie. Les biographies sont souvent utilisées pour en apprendre davantage sur des personnalités célèbres telles que des musiciens, des acteurs ou des politiciens. \"Steve Jobs\" de Walter Isaacson est un exemple de biographie bien connue.",
                            DomainName = "Biographie "
                        },
                        new
                        {
                            Id = 3,
                            Description = "Les livres de fantasy sont des histoires qui se déroulent dans des mondes imaginaires remplis de magie et de créatures fantastiques. Ils peuvent se concentrer sur des aventures, des quêtes ou des batailles épiques. \"Le Seigneur des Anneaux\" de J.R.R. Tolkien est un exemple bien connu de livre de fantasy.",
                            DomainName = "Fantasy"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Les livres de romance sont des histoires d'amour passionnantes et souvent dramatiques. Ils peuvent se concentrer sur des relations amoureuses, des triangles amoureux et des obstacles à surmonter. \"Orgueil et Préjugés\" de Jane Austen est un exemple classique de livre de romance.",
                            DomainName = "Romance "
                        },
                        new
                        {
                            Id = 5,
                            Description = "Les livres policiers sont des histoires qui se concentrent sur les enquêtes et les résolutions de crimes. Les auteurs de livres policiers doivent créer des intrigues compliquées et des personnages convaincants pour garder les lecteurs captivés. \"Le Silence des Agneaux\" de Thomas Harris est un exemple célèbre de livre policier.",
                            DomainName = "Policier "
                        },
                        new
                        {
                            Id = 6,
                            Description = "Les autobiographies sont des livres qui racontent la vie d'une personne écrite par elle-même. Ils peuvent se concentrer sur des moments clés de la vie de l'auteur, des leçons apprises ou des défis surmontés. \"Born a Crime\" de Trevor Noah est un exemple récent de livre autobiographique qui raconte l'histoire de l'humoriste et présentateur sud-africain.",
                            DomainName = "Autobiographie "
                        });
                });

            modelBuilder.Entity("AuthorBook", b =>
                {
                    b.Property<int>("AuthorsId")
                        .HasColumnType("int");

                    b.Property<int>("BooksId")
                        .HasColumnType("int");

                    b.HasKey("AuthorsId", "BooksId");

                    b.HasIndex("BooksId");

                    b.ToTable("AuthorBook");

                    b.HasData(
                        new
                        {
                            AuthorsId = 1,
                            BooksId = 1
                        });
                });

            modelBuilder.Entity("BookKeyword", b =>
                {
                    b.Property<int>("BooksId")
                        .HasColumnType("int");

                    b.Property<int>("KeyWordsId")
                        .HasColumnType("int");

                    b.HasKey("BooksId", "KeyWordsId");

                    b.HasIndex("KeyWordsId");

                    b.ToTable("BookKeyword");

                    b.HasData(
                        new
                        {
                            BooksId = 1,
                            KeyWordsId = 2
                        });
                });

            modelBuilder.Entity("BookTheme", b =>
                {
                    b.Property<int>("BooksId")
                        .HasColumnType("int");

                    b.Property<int>("ThemesId")
                        .HasColumnType("int");

                    b.HasKey("BooksId", "ThemesId");

                    b.HasIndex("ThemesId");

                    b.ToTable("BookTheme");

                    b.HasData(
                        new
                        {
                            BooksId = 1,
                            ThemesId = 1
                        });
                });

            modelBuilder.Entity("AuthorBook", b =>
                {
                    b.HasOne("AspMvcBiblio.Entities.Author", null)
                        .WithMany()
                        .HasForeignKey("AuthorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AspMvcBiblio.Entities.Book", null)
                        .WithMany()
                        .HasForeignKey("BooksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookKeyword", b =>
                {
                    b.HasOne("AspMvcBiblio.Entities.Book", null)
                        .WithMany()
                        .HasForeignKey("BooksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AspMvcBiblio.Entities.Keyword", null)
                        .WithMany()
                        .HasForeignKey("KeyWordsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookTheme", b =>
                {
                    b.HasOne("AspMvcBiblio.Entities.Book", null)
                        .WithMany()
                        .HasForeignKey("BooksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AspMvcBiblio.Entities.Theme", null)
                        .WithMany()
                        .HasForeignKey("ThemesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
